#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if xrandr -q | grep 'DP-1 connected'; then
xrandr --output DP-1 --mode 1440x900 -r 75 --right-of HDMI-1
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
else
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
fi
xrandr --output HDMI-1 --primary --mode 1920x1080 -r 75

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
# bspc config normal_border_color \#b3b1ad
# bspc config active_border_color \#b3b1ad
bspc config focused_border_color \#6e7681
bspc config window_gap          0
bspc config top_padding 0
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a neofetch-alacritty state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Picture-in-Picture state=floating

#AutoStart applications
sxhkd &
picom &
nitrogen --restore &
dunst --config $HOME/.config/dunst/dunstrc &
polybar main &
polybar secondary &
clipit &
# node ~/stream-tool/build/server.js
#alacritty -e sudo -b /home/apollo/Documentos/projects/automacao_mouse_teclado/venv/bin/python /home/apollo/Documentos/projects/automacao_mouse_teclado/main.py &
http-server /home/apollo/twitch_bot_frontend --port 8123&
